#:schema ../../schemas/vellum.schema.json

[theme]
foreground = "#d8dee9"
background = "#2e3440"
selection_foreground = "#2e3440"
selection_background = "#88c0d0"
border = "#4c566a"
mode_foreground = "#2e3440"
insert_mode_background = "#a3be8c"
normal_mode_background = "#ebcb8b"

[theme.colors]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"
bright_black = "#4c566a"
bright_red = "#bf616a"
bright_green = "#a3be8c"
bright_yellow = "#ebcb8b"
bright_blue = "#81a1c1"
bright_magenta = "#b48ead"
bright_cyan = "#8fbcbb"
bright_white = "#eceff4"
