#:schema ../schemas/global.schema.json

[search]
title = "Vellum"

[input]
vim = true
start_mode = "insert"

[frecency]
enabled = true
max_entries = 1000

[keybindings]
enabled = true
down = ["down", "ctrl-n"]
up = ["up", "ctrl-p"]

[filters]
label = "filter"
mode = "ctrl-g"
clear = "a"

[item]
padding = 1
