#:schema ../schemas/global.schema.json

[input]
vim = true
start_mode = "insert"

[frecency]
enabled = true
max_entries = 1000

[keybindings]
enabled = true
down = ["down", "ctrl-n"]
up = ["up", "ctrl-p"]

[item]
padding = 1
