#:schema https://raw.githubusercontent.com/dkarter/vellum/refs/heads/main/schemas/vellum.schema.json

[search]
title = "Files"
placeholder = "Find a file..."

[source]
builtin = "files"

[item]
value = "$path"
template = [
  [
    { token = "$icon", fg = "$icon_color", searchable = false },
    " ",
    { token = "$parent_prefix", fg = "#565f89" },
    { token = "$name", bold = true },
  ],
]

[theme]
foreground = "#c0caf5"
background = "#1a1b26"
selection_foreground = "#c0caf5"
selection_background = "#283457"
border = "#565f89"
mode_foreground = "#1a1b26"
insert_mode_background = "#9ece6a"
normal_mode_background = "#e0af68"
